<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="7" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-30T00:42:42 IST" name="All Test Suite" finished-at="2023-03-30T00:42:47 IST" duration-ms="5306">
    <groups>
    </groups>
    <test started-at="2023-03-30T00:42:42 IST" name="/Users/varsha.tiwari/Documents/Appium_Resources/ToDoAppUIAuotmation" finished-at="2023-03-30T00:42:47 IST" duration-ms="5306">
      <class name="testScripts.HomePageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testScripts.HomePageTest@37574691]" started-at="2023-03-30T00:42:42 IST" name="setUp" finished-at="2023-03-30T00:42:42 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testAddSingleItemToTheList()[pri:0, instance:testScripts.HomePageTest@37574691]" started-at="2023-03-30T00:42:42 IST" name="testAddSingleItemToTheList" finished-at="2023-03-30T00:42:47 IST" duration-ms="5018" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddSingleItemToTheList -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testScripts.HomePageTest@37574691]" started-at="2023-03-30T00:42:47 IST" name="tearDown" finished-at="2023-03-30T00:42:47 IST" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at testScripts.BaseTest.tearDown(BaseTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:282)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:83)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:114)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testScripts.HomePageTest -->
    </test> <!-- /Users/varsha.tiwari/Documents/Appium_Resources/ToDoAppUIAuotmation -->
  </suite> <!-- All Test Suite -->
</testng-results>
